### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by shuvadipkhanra** [genesis-release-r-ccs/genesis#1]
**During installation encountered by following issues.

Probably fortran issue @argument mismatch issue. how to resolve this problem?**

(base) shuvadip@shuvadip:~/Downloads/genesis-2.1.2$ ./configure --enable-single --enable-gpu 

    24 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 62 registers, 564 bytes cmem[0], 12 bytes cmem[2]
ptxas info    : Compiling entry function '_Z56kern_compute_energy_nonbond_table_linear_univ_energy_sumPdPKdiiii' for 'sm_62'
ptxas info    : Function properties for _Z56kern_compute_energy_nonbond_table_linear_univ_energy_sumPdPKdiiii
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 30 registers, 1280 bytes smem, 352 bytes cmem[0]
ptxas info    : Compiling entry function 
mpif90  -I. -I../../src  -I../lib -O3 -ffast-math -march=native -ffree-line-length-none -fallow-argument-mismatch -fopenmp   -c sp_enefunc_table.f90
mpif90  -I. -I../../src  -I../lib -O3 -ffast-math -march=native -ffree-line-length-none -fallow-argument-mismatch -fopenmp   -c sp_grest_energy.f90
mpif90  -I. -I../../src  -I../lib -O3 -ffast-math -march=native -ffree-line-length-none -fallow-argument-mismatch -fopenmp   -c sp_fep_energy.f90
mpif90  -I. -I../../src  -I../lib -O3 -ffast-math -march=native -ffree-line-length-none -fallow-argument-mismatch -fopenmp   -c sp_domain.f90
cpp -traditional-cpp -traditional -DHAVE_CONFIG_H sp_enefunc_charmm.fpp sp_enefunc_charmm.f90
mpif90  -I. -I../../src  -I../lib -O3 -ffast-math -march=native -ffree-line-length-none -fallow-argument-mismatch -fopenmp   -c sp_enefunc_charmm.f90
cpp -traditional-cpp -traditional -DHAVE_CONFIG_H sp_alchemy.fpp sp_alchemy.f90
mpif90  -I. -I../../src  -I../lib -O3 -ffast-math -march=native -ffree-line-length-none -fallow-argument-mismatch -fopenmp   -c sp_alchemy.f90
cpp -traditional-cpp -traditional -DHAVE_CONFIG_H sp_fep_topology.fpp sp_fep_topology.f90
mpif90  -I. -I../../src  -I../lib -O3 -ffast-math -march=native -ffree-line-length-none -fallow-argument-mismatch -fopenmp   -c sp_fep_topology.f90
	../lib/lib.a  -fopenmp  -llapack -lblas -L/usr/local/cuda-11.8/lib64 -lcudart -lstdc++ 
make[4]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
make[3]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
make[3]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[3]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[2]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[1]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[1]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2'

**Comment by chig** [comment]
I could not tell what the problem was from the message you indicated.
Could you share us the log files of configure and make?
The config.log is located  in the directory where you executed './configure'.
As for log of make, please execute the following commands.
`make clean
make > make.log 2>&1
`
 Then, you can find 'make.log'. 
please do not do 'make -j n' at this time. The log will be difficult to understand.

**Comment by shuvadipkhanra** [comment]
[config.log](https://github.com/genesis-release-r-ccs/genesis/files/15127560/config.log)
[make.log](https://github.com/genesis-release-r-ccs/genesis/files/15127561/make.log)
Kindly fiend the attachments...

**Comment by chig** [comment]
Thanks. I check the log files. However, it looks OK while nvcc shows so many warnings.
(Since your CUDA is new, so it warns against GENESIS' code for older cards, but there should be no problem.)
Please execute 'make install', then you can find bin/spdyn in the directory.

**Comment by shuvadipkhanra** [comment]
ok sir.. doing it

**Comment by shuvadipkhanra** [comment]
(base) shuvadip@shuvadip:~/Downloads/genesis-2.1.2$ make install
Making install in src
make[1]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
Making install in lib
make[2]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[3]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[4]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[4]: Nothing to be done for 'install-exec-am'.
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[3]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[2]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
Making install in spdyn
make[2]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
Making install in ../lib
make[3]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[4]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[5]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[4]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
make[3]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/lib'
Making install in .
make[3]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
make[4]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
 /usr/bin/mkdir -p '/home/shuvadip/Downloads/genesis-2.1.2//bin'
  /usr/bin/install -c spdyn '/home/shuvadip/Downloads/genesis-2.1.2//bin'
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
make[3]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
make[2]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src/spdyn'
make[2]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[3]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[2]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[1]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2/src'
make[1]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2'
make[2]: Entering directory '/home/shuvadip/Downloads/genesis-2.1.2'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2'
make[1]: Leaving directory '/home/shuvadip/Downloads/genesis-2.1.2'

**Comment by shuvadipkhanra** [comment]
yes found bin folder

(base) shuvadip@shuvadip:~/Downloads/genesis-2.1.2/bin$ l
spdyn*
(base) shuvadip@shuvadip:~/Downloads/genesis-2.1.2/bin$ ./spdyn 
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
 
# normal usage
  % mpirun -np XX ./spdyn INP
 
# check control parameters of md
  % ./spdyn -h ctrl md
 
# check control parameters of min
  % ./spdyn -h ctrl min
 
# check control parameters of remd
  % ./spdyn -h ctrl remd
 
# check control parameters of rpath
  % ./spdyn -h ctrl rpath
 
# check all control parameters of md
  % ./spdyn -h ctrl_all md
 
# check all control parameters of min
  % ./spdyn -h ctrl_all min
 
# check all control parameters of remd
  % ./spdyn -h ctrl_all remd
 
# check all control parameters of rpath
  % ./spdyn -h ctrl_all rpath

**Comment by shuvadipkhanra** [comment]
i am interested to calculate Absolute ligand binding profile. I have experience with gromacs but Charmm gui yet not support so interested to calculate MD and ABE calculation. Thus spdyn is sufficient for the same?

**Comment by chig** [comment]
I'm sorry that I'm not sure about it. Please check our tutorials in website or manual.
https://www.r-ccs.riken.jp/labs/cbrt/tutorials2022/
This is where we accept questions/reports for the GENESIS code, so please check the website for instructions on how to use it.
