### ISSUE TITLE
Errors in running genesis-2.1.4 with GPU

### ISSUE THREAD

**Issue by mersalas** [genesis-release-r-ccs/genesis#2]
I am following your tutorials specially for GaMD. I did the level 1 tutorial in CPU and just copied the files needed for the GaMD from tutorial-3.2 into the folder where I installed genesis with GPU. I am using Ubuntu 24.04, nvidia-driver-550, CUDA 11.7, gcc-10, and gfortran-10. The software genesis-2.1.4 was successfully installed based on the regression_test. When I ran this from the GaMD tutorial: 
$GENESIS_BIN_DIR/spdyn -np 8 run1.inp > run1.out
I got this error: 
bash: ../../../genesis_gpu/Programs/genesis-2.1.4/bin//spdyn: No such file or directory
so I tried this: 
export GENESIS_BIN_DIR=/home/rlsalas/genesis_gpu/Programs/genesis-2.1.4/bin
mpirun -n 8 $GENESIS_BIN_DIR/spdyn run1.inp > run1.out
but got this errors:
Error in gpu_get_device_count at gpu_sp_energy.cu:10868
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

Error in gpu_get_device_count at gpu_sp_energy.cu:10868
Error in gpu_get_device_count at gpu_sp_energy.cu:10868
Error in gpu_get_device_count at gpu_sp_energy.cu:10868
Error in gpu_get_device_count at gpu_sp_energy.cu:10868
Error in gpu_get_device_count at gpu_sp_energy.cu:10868

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[51310,1],5]
  Exit code:    255

**Comment by chig** [comment]
Hello,
The message indicates that genesis does not find any GPU card on the node. (This part is simply calling a CUDA function.)
Could you check your GPU card on the machine via 'nvidia-smi'?

**Comment by mersalas** [comment]
It's working already. Thank you!
